name: Spotify Now Playing
on:
  schedule:
    - cron: '*/2 * * * *'  # runs every 5 minutes
  workflow_dispatch:

jobs:
  spotify:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Spotify badge
        uses: anuraghazra/spotify-github-profile-action@v2
        with:
          spotify_client_id: ${{ secrets.5c16a11041c94c76b3c3c8ed2ca04aaf }}
          spotify_client_secret: ${{ secrets.f4a9a3435a934a18880808be4417ee45 }}
          spotify_refresh_token: ${{ secrets.AQAWxJVvKq2yy9U3FKj2HBOdoJXH7pUNkkHqTLt4Klcjr_UkHrylyXB6TNgul2CZxOkwC3CGblEDrAJnip-_R63TqNs4an-JjGYin5aZU0WwK3Ws-VKDUNAxKyojRFsKEEI }}
          theme: default
          cover_image: true
          show_offline: true
          background_color: 0d1117
